dist: trusty
language: node_js

node_js:
    - "7"

script:
    # - npm run lint
    - npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local_dir: dist
    verbose: true
    on:
        branch: master
